shared:
  settings:
    email:
      addresses: [kraune@yahooinc.com]
      statuses: [SUCCESS, FAILURE]

jobs:
  link-checker-frontpage:
    requires: [~pr, ~commit]
    image: ruby:2.6
    environment:
      USER_SHELL_BIN: bash
    annotations:
      screwdriver.cd/buildPeriodically: H H(0-5) * * 1-5 # some time between 12:00 AM UTC (midnight) to 5:59 AM UTC Mon-Fri
    steps:
      - install-deps: |
          gem install bundler
      - check-links: |
          export LANG=C.UTF-8
          bundle install
          bundle exec jekyll build
          bundle exec htmlproofer \
            --assume-extension .html \
            --enforce_https false \
            --typhoeus '{"connecttimeout": 10, "timeout": 30}' \
            --hydra '{"max_concurrency": 1}' \
            _site
