shared:
  settings:
    email:
      addresses: [kraune@yahooinc.com]
      statuses: [SUCCESS, FAILURE]

jobs:
  link-checker-frontpage:
    requires: [~pr, ~commit]
    image: ruby:2.6
    environment:
      USER_SHELL_BIN: bash
    annotations:
      screwdriver.cd/buildPeriodically: H 0 * * *
    steps:
      - install-deps: |
          gem install bundler
      - check-links: |
          export LANG=C.UTF-8
          bundle install
          bundle exec jekyll build
          bundle exec htmlproofer \
            --assume-extension \
            --check-html \
            --typhoeus '{"connecttimeout": 10, "timeout": 30}' \
            --hydra '{"max_concurrency": 1}' \
            _site
